name: Test composite actions
description: A short description of the action.
inputs:
  mandatoryParameter:
    required: true
    description: This parameter is very-very important!
  redundantParameter:
    required: false
    description: I don't need this parameter at all
runs:
  using: "composite"
  steps:
    - id: step1
      name: first step
      run: echo "This is first action, $INPUT_TEST_INPUT"
      shell: bash
    - id: step2
      name: second step
      run: second-action.sh
      shell: sh